# ==========================================
# Dependencies Stage
# ==========================================
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

# ==========================================
# Build Stage
# ==========================================
FROM node:20-alpine AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js telemetry disable
ENV NEXT_TELEMETRY_DISABLED 1

# Execute Next.js standalone build
RUN npm run build

# ==========================================
# Production Stage
# ==========================================
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Set correct permissions for Next.js cache
RUN mkdir .next && chown nextjs:nodejs .next

# Copy the minimal standalone output natively generated by Next.js
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
# Copy static assets required for CSS/JS execution
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
# Copy public folder for static images (if any exist)
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

# Drop root privileges
USER nextjs

EXPOSE 3000
ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

# Execute standard Node.js server (bypasses NPM overhead)
CMD ["node", "server.js"]
