// AUTO-GENERATED SYNTHETIC DATA FOR KLMCE ERP
export const STUDENTS = [
    {
        "id": "STU2024001",
        "name": "Arjun Sharma",
        "email": "arjun.sharma@student.klmce.edu.in",
        "phone": "+91 94012 39256",
        "gender": "M",
        "dob": "2000-12-04",
        "region": "Madurai",
        "department": "Information Technology",
        "cgpa": 7.89,
        "year": 1,
        "attendance_pct": 77,
        "fee_status": "Paid",
        "status": "Active"
    },
    {
        "id": "STU2024002",
        "name": "Naveen Pillai",
        "email": "naveen.pillai@student.klmce.edu.in",
        "phone": "+91 98928 64987",
        "gender": "M",
        "dob": "2000-08-19",
        "region": "Salem",
        "department": "Computer Science",
        "cgpa": 9.0,
        "year": 2,
        "attendance_pct": 97,
        "fee_status": "Overdue",
        "status": "Active"
    },
    {
        "id": "STU2024003",
        "name": "Swathi Pillai",
        "email": "swathi.pillai@student.klmce.edu.in",
        "phone": "+91 95514 23396",
        "gender": "F",
        "dob": "1999-07-04",
        "region": "Bangalore",
        "department": "Electrical",
        "cgpa": 8.49,
        "year": 1,
        "attendance_pct": 98,
        "fee_status": "Overdue",
        "status": "Active"
    },
    {
        "id": "STU2024004",
        "name": "Sneha Rao",
        "email": "sneha.rao@student.klmce.edu.in",
        "phone": "+91 94803 92397",
        "gender": "F",
        "dob": "2003-06-19",
        "region": "Trichy",
        "department": "Electronics",
        "cgpa": 6.73,
        "year": 2,
        "attendance_pct": 99,
        "fee_status": "Pending",
        "status": "Active"
    },
    {
        "id": "STU2024005",
        "name": "Aditya Rajan",
        "email": "aditya.rajan@student.klmce.edu.in",
        "phone": "+91 94554 69429",
        "gender": "M",
        "dob": "2004-06-06",
        "region": "Bangalore",
        "department": "Electrical",
        "cgpa": 7.19,
        "year": 3,
        "attendance_pct": 97,
        "fee_status": "Paid",
        "status": "Active"
    },
    {
        "id": "STU2024006",
        "name": "Siddharth Gounder",
        "email": "siddharth.gounder@student.klmce.edu.in",
        "phone": "+91 96216 45382",
        "gender": "M",
        "dob": "2004-12-18",
        "region": "Trichy",
        "department": "Electronics",
        "cgpa": 7.57,
        "year": 1,
        "attendance_pct": 82,
        "fee_status": "Paid",
        "status": "Active"
    },
    {
        "id": "STU2024007",
        "name": "Aishwarya Nair",
        "email": "aishwarya.nair@student.klmce.edu.in",
        "phone": "+91 93456 84341",
        "gender": "F",
        "dob": "2004-06-07",
        "region": "Kochi",
        "department": "Civil",
        "cgpa": 9.42,
        "year": 4,
        "attendance_pct": 79,
        "fee_status": "Pending",
        "status": "Active"
    },
    {
        "id": "STU2024008",
        "name": "Naveen Rao",
        "email": "naveen.rao@student.klmce.edu.in",
        "phone": "+91 94304 86622",
        "gender": "M",
        "dob": "2002-10-13",
        "region": "Bangalore",
        "department": "Mechanical",
        "cgpa": 9.79,
        "year": 2,
        "attendance_pct": 91,
        "fee_status": "Overdue",
        "status": "Active"
    },
    {
        "id": "STU2024009",
        "name": "Aditya Reddy",
        "email": "aditya.reddy@student.klmce.edu.in",
        "phone": "+91 92621 99192",
        "gender": "M",
        "dob": "2002-10-03",
        "region": "Hyderabad",
        "department": "Civil",
        "cgpa": 8.47,
        "year": 4,
        "attendance_pct": 91,
        "fee_status": "Pending",
        "status": "Active"
    },
    {
        "id": "STU2024010",
        "name": "Naveen Sharma",
        "email": "naveen.sharma@student.klmce.edu.in",
        "phone": "+91 95573 24621",
        "gender": "M",
        "dob": "2001-07-06",
        "region": "Kochi",
        "department": "Computer Science",
        "cgpa": 9.65,
        "year": 3,
        "attendance_pct": 91,
        "fee_status": "Paid",
        "status": "Active"
    },
    {
        "id": "STU2024011",
        "name": "Sruthi Pillai",
        "email": "sruthi.pillai@student.klmce.edu.in",
        "phone": "+91 92504 59009",
        "gender": "F",
        "dob": "2005-03-18",
        "region": "Chennai",
        "department": "Information Technology",
        "cgpa": 7.57,
        "year": 1,
        "attendance_pct": 78,
        "fee_status": "Pending",
        "status": "Active"
    },
    {
        "id": "STU2024012",
        "name": "Karthik Krishnan",
        "email": "karthik.krishnan@student.klmce.edu.in",
        "phone": "+91 99295 20322",
        "gender": "M",
        "dob": "1999-12-16",
        "region": "Madurai",
        "department": "Information Technology",
        "cgpa": 9.03,
        "year": 2,
        "attendance_pct": 96,
        "fee_status": "Overdue",
        "status": "Active"
    },
    {
        "id": "STU2024013",
        "name": "Sruthi Murthy",
        "email": "sruthi.murthy@student.klmce.edu.in",
        "phone": "+91 93470 80686",
        "gender": "F",
        "dob": "2005-12-23",
        "region": "Trichy",
        "department": "Electronics",
        "cgpa": 7.53,
        "year": 3,
        "attendance_pct": 89,
        "fee_status": "Overdue",
        "status": "Active"
    },
    {
        "id": "STU2024014",
        "name": "Rohit Nair",
        "email": "rohit.nair@student.klmce.edu.in",
        "phone": "+91 95539 12757",
        "gender": "M",
        "dob": "2003-09-08",
        "region": "Trichy",
        "department": "Computer Science",
        "cgpa": 6.73,
        "year": 1,
        "attendance_pct": 82,
        "fee_status": "Paid",
        "status": "Active"
    },
    {
        "id": "STU2024015",
        "name": "Sneha Verma",
        "email": "sneha.verma@student.klmce.edu.in",
        "phone": "+91 93899 46500",
        "gender": "F",
        "dob": "2004-08-07",
        "region": "Coimbatore",
        "department": "Electronics",
        "cgpa": 9.59,
        "year": 4,
        "attendance_pct": 82,
        "fee_status": "Overdue",
        "status": "Warning"
    },
    {
        "id": "STU2024016",
        "name": "Aditya Rao",
        "email": "aditya.rao@student.klmce.edu.in",
        "phone": "+91 97062 56438",
        "gender": "M",
        "dob": "2002-07-15",
        "region": "Chennai",
        "department": "Electronics",
        "cgpa": 8.66,
        "year": 1,
        "attendance_pct": 76,
        "fee_status": "Overdue",
        "status": "Active"
    },
    {
        "id": "STU2024017",
        "name": "Rohit Pillai",
        "email": "rohit.pillai@student.klmce.edu.in",
        "phone": "+91 93116 80292",
        "gender": "M",
        "dob": "2002-03-14",
        "region": "Coimbatore",
        "department": "Electrical",
        "cgpa": 8.03,
        "year": 1,
        "attendance_pct": 89,
        "fee_status": "Paid",
        "status": "Active"
    },
    {
        "id": "STU2024018",
        "name": "Rahul Krishnan",
        "email": "rahul.krishnan@student.klmce.edu.in",
        "phone": "+91 92724 63269",
        "gender": "M",
        "dob": "2002-08-07",
        "region": "Hyderabad",
        "department": "Computer Science",
        "cgpa": 7.04,
        "year": 1,
        "attendance_pct": 87,
        "fee_status": "Pending",
        "status": "Warning"
    },
    {
        "id": "STU2024019",
        "name": "Lakshmi Rao",
        "email": "lakshmi.rao@student.klmce.edu.in",
        "phone": "+91 97973 30289",
        "gender": "F",
        "dob": "2000-05-07",
        "region": "Chennai",
        "department": "Information Technology",
        "cgpa": 8.93,
        "year": 1,
        "attendance_pct": 98,
        "fee_status": "Pending",
        "status": "Active"
    },
    {
        "id": "STU2024020",
        "name": "Prashant Deshmukh",
        "email": "prashant.deshmukh@student.klmce.edu.in",
        "phone": "+91 98238 79615",
        "gender": "M",
        "dob": "2000-01-17",
        "region": "Madurai",
        "department": "Mechanical",
        "cgpa": 6.73,
        "year": 1,
        "attendance_pct": 96,
        "fee_status": "Paid",
        "status": "Warning"
    },
    {
        "id": "STU2024021",
        "name": "Prashant Krishnan",
        "email": "prashant.krishnan@student.klmce.edu.in",
        "phone": "+91 99485 87924",
        "gender": "M",
        "dob": "1999-10-03",
        "region": "Hyderabad",
        "department": "Electronics",
        "cgpa": 8.43,
        "year": 3,
        "attendance_pct": 83,
        "fee_status": "Paid",
        "status": "Active"
    },
    {
        "id": "STU2024022",
        "name": "Vijay Rajan",
        "email": "vijay.rajan@student.klmce.edu.in",
        "phone": "+91 92144 98039",
        "gender": "M",
        "dob": "2004-05-15",
        "region": "Bangalore",
        "department": "Computer Science",
        "cgpa": 6.53,
        "year": 1,
        "attendance_pct": 77,
        "fee_status": "Paid",
        "status": "Active"
    },
    {
        "id": "STU2024023",
        "name": "Praveen Nair",
        "email": "praveen.nair@student.klmce.edu.in",
        "phone": "+91 94002 58434",
        "gender": "M",
        "dob": "2001-03-15",
        "region": "Salem",
        "department": "Information Technology",
        "cgpa": 9.75,
        "year": 1,
        "attendance_pct": 96,
        "fee_status": "Pending",
        "status": "Active"
    },
    {
        "id": "STU2024024",
        "name": "Vijay Rao",
        "email": "vijay.rao@student.klmce.edu.in",
        "phone": "+91 91753 82512",
        "gender": "M",
        "dob": "2000-05-10",
        "region": "Trichy",
        "department": "Electronics",
        "cgpa": 7.63,
        "year": 3,
        "attendance_pct": 91,
        "fee_status": "Overdue",
        "status": "Active"
    },
    {
        "id": "STU2024025",
        "name": "Rahul Murthy",
        "email": "rahul.murthy@student.klmce.edu.in",
        "phone": "+91 94533 15778",
        "gender": "M",
        "dob": "1999-06-25",
        "region": "Coimbatore",
        "department": "Electronics",
        "cgpa": 9.73,
        "year": 2,
        "attendance_pct": 98,
        "fee_status": "Overdue",
        "status": "Warning"
    },
    {
        "id": "STU2024026",
        "name": "Aditya Nair",
        "email": "aditya.nair@student.klmce.edu.in",
        "phone": "+91 92442 81511",
        "gender": "M",
        "dob": "1999-06-19",
        "region": "Coimbatore",
        "department": "Civil",
        "cgpa": 6.92,
        "year": 3,
        "attendance_pct": 86,
        "fee_status": "Paid",
        "status": "Active"
    },
    {
        "id": "STU2024027",
        "name": "Rohit Rao",
        "email": "rohit.rao@student.klmce.edu.in",
        "phone": "+91 95794 83385",
        "gender": "M",
        "dob": "2005-07-20",
        "region": "Coimbatore",
        "department": "Mechanical",
        "cgpa": 9.35,
        "year": 2,
        "attendance_pct": 88,
        "fee_status": "Paid",
        "status": "Active"
    },
    {
        "id": "STU2024028",
        "name": "Lakshmi Krishnan",
        "email": "lakshmi.krishnan@student.klmce.edu.in",
        "phone": "+91 94371 30866",
        "gender": "F",
        "dob": "2005-12-04",
        "region": "Hyderabad",
        "department": "Computer Science",
        "cgpa": 9.33,
        "year": 2,
        "attendance_pct": 81,
        "fee_status": "Overdue",
        "status": "Active"
    },
    {
        "id": "STU2024029",
        "name": "Shruti Krishnan",
        "email": "shruti.krishnan@student.klmce.edu.in",
        "phone": "+91 90387 96511",
        "gender": "F",
        "dob": "2000-07-11",
        "region": "Salem",
        "department": "Computer Science",
        "cgpa": 9.69,
        "year": 3,
        "attendance_pct": 86,
        "fee_status": "Overdue",
        "status": "Active"
    },
    {
        "id": "STU2024030",
        "name": "Aditya Sharma",
        "email": "aditya.sharma@student.klmce.edu.in",
        "phone": "+91 92925 86099",
        "gender": "M",
        "dob": "2001-01-04",
        "region": "Hyderabad",
        "department": "Electrical",
        "cgpa": 8.9,
        "year": 3,
        "attendance_pct": 88,
        "fee_status": "Paid",
        "status": "Warning"
    },
    {
        "id": "STU2024031",
        "name": "Vijay Iyer",
        "email": "vijay.iyer@student.klmce.edu.in",
        "phone": "+91 97144 10221",
        "gender": "M",
        "dob": "2003-09-22",
        "region": "Trichy",
        "department": "Electrical",
        "cgpa": 7.92,
        "year": 3,
        "attendance_pct": 94,
        "fee_status": "Pending",
        "status": "Active"
    },
    {
        "id": "STU2024032",
        "name": "Sruthi Singh",
        "email": "sruthi.singh@student.klmce.edu.in",
        "phone": "+91 96691 52753",
        "gender": "F",
        "dob": "2002-12-10",
        "region": "Coimbatore",
        "department": "Mechanical",
        "cgpa": 7.89,
        "year": 4,
        "attendance_pct": 96,
        "fee_status": "Paid",
        "status": "Active"
    },
    {
        "id": "STU2024033",
        "name": "Kavya Singh",
        "email": "kavya.singh@student.klmce.edu.in",
        "phone": "+91 94700 37549",
        "gender": "F",
        "dob": "2002-10-20",
        "region": "Bangalore",
        "department": "Civil",
        "cgpa": 7.96,
        "year": 2,
        "attendance_pct": 91,
        "fee_status": "Overdue",
        "status": "Active"
    },
    {
        "id": "STU2024034",
        "name": "Ashwin Verma",
        "email": "ashwin.verma@student.klmce.edu.in",
        "phone": "+91 95491 22240",
        "gender": "M",
        "dob": "2005-04-22",
        "region": "Salem",
        "department": "Mechanical",
        "cgpa": 9.16,
        "year": 2,
        "attendance_pct": 75,
        "fee_status": "Paid",
        "status": "Active"
    },
    {
        "id": "STU2024035",
        "name": "Sneha Gounder",
        "email": "sneha.gounder@student.klmce.edu.in",
        "phone": "+91 96790 92544",
        "gender": "F",
        "dob": "2003-04-23",
        "region": "Hyderabad",
        "department": "Civil",
        "cgpa": 7.82,
        "year": 2,
        "attendance_pct": 95,
        "fee_status": "Paid",
        "status": "Active"
    },
    {
        "id": "STU2024036",
        "name": "Shruti Menon",
        "email": "shruti.menon@student.klmce.edu.in",
        "phone": "+91 98486 70889",
        "gender": "F",
        "dob": "1999-09-08",
        "region": "Madurai",
        "department": "Civil",
        "cgpa": 6.94,
        "year": 4,
        "attendance_pct": 96,
        "fee_status": "Pending",
        "status": "Warning"
    },
    {
        "id": "STU2024037",
        "name": "Ananya Menon",
        "email": "ananya.menon@student.klmce.edu.in",
        "phone": "+91 97777 68991",
        "gender": "F",
        "dob": "2001-04-27",
        "region": "Salem",
        "department": "Information Technology",
        "cgpa": 8.1,
        "year": 2,
        "attendance_pct": 83,
        "fee_status": "Overdue",
        "status": "Active"
    },
    {
        "id": "STU2024038",
        "name": "Shruti Sharma",
        "email": "shruti.sharma@student.klmce.edu.in",
        "phone": "+91 95502 51904",
        "gender": "F",
        "dob": "2003-02-05",
        "region": "Coimbatore",
        "department": "Mechanical",
        "cgpa": 7.76,
        "year": 2,
        "attendance_pct": 97,
        "fee_status": "Paid",
        "status": "Active"
    },
    {
        "id": "STU2024039",
        "name": "Lakshmi Patel",
        "email": "lakshmi.patel@student.klmce.edu.in",
        "phone": "+91 98890 71069",
        "gender": "F",
        "dob": "2002-01-07",
        "region": "Hyderabad",
        "department": "Civil",
        "cgpa": 9.49,
        "year": 1,
        "attendance_pct": 99,
        "fee_status": "Overdue",
        "status": "Warning"
    },
    {
        "id": "STU2024040",
        "name": "Praveen Singh",
        "email": "praveen.singh@student.klmce.edu.in",
        "phone": "+91 96389 64921",
        "gender": "M",
        "dob": "2003-12-24",
        "region": "Trichy",
        "department": "Civil",
        "cgpa": 7.22,
        "year": 4,
        "attendance_pct": 90,
        "fee_status": "Paid",
        "status": "Warning"
    },
    {
        "id": "STU2024041",
        "name": "Pooja Menon",
        "email": "pooja.menon@student.klmce.edu.in",
        "phone": "+91 97657 26728",
        "gender": "F",
        "dob": "2003-09-01",
        "region": "Hyderabad",
        "department": "Information Technology",
        "cgpa": 8.36,
        "year": 1,
        "attendance_pct": 77,
        "fee_status": "Overdue",
        "status": "Active"
    },
    {
        "id": "STU2024042",
        "name": "Anjali Iyer",
        "email": "anjali.iyer@student.klmce.edu.in",
        "phone": "+91 94262 59689",
        "gender": "F",
        "dob": "2001-04-15",
        "region": "Bangalore",
        "department": "Electrical",
        "cgpa": 9.01,
        "year": 4,
        "attendance_pct": 83,
        "fee_status": "Overdue",
        "status": "Active"
    },
    {
        "id": "STU2024043",
        "name": "Vishal Kumar",
        "email": "vishal.kumar@student.klmce.edu.in",
        "phone": "+91 98837 16826",
        "gender": "M",
        "dob": "2001-04-21",
        "region": "Madurai",
        "department": "Electronics",
        "cgpa": 6.63,
        "year": 1,
        "attendance_pct": 82,
        "fee_status": "Paid",
        "status": "Active"
    },
    {
        "id": "STU2024044",
        "name": "Rohit Reddy",
        "email": "rohit.reddy@student.klmce.edu.in",
        "phone": "+91 97758 97747",
        "gender": "M",
        "dob": "1999-10-07",
        "region": "Kochi",
        "department": "Electronics",
        "cgpa": 7.35,
        "year": 3,
        "attendance_pct": 80,
        "fee_status": "Paid",
        "status": "Active"
    },
    {
        "id": "STU2024045",
        "name": "Neha Naidu",
        "email": "neha.naidu@student.klmce.edu.in",
        "phone": "+91 90420 50888",
        "gender": "F",
        "dob": "2003-11-13",
        "region": "Hyderabad",
        "department": "Electronics",
        "cgpa": 7.15,
        "year": 2,
        "attendance_pct": 78,
        "fee_status": "Pending",
        "status": "Active"
    },
    {
        "id": "STU2024046",
        "name": "Praveen Rao",
        "email": "praveen.rao@student.klmce.edu.in",
        "phone": "+91 97018 96706",
        "gender": "M",
        "dob": "2001-02-17",
        "region": "Bangalore",
        "department": "Computer Science",
        "cgpa": 9.3,
        "year": 4,
        "attendance_pct": 78,
        "fee_status": "Overdue",
        "status": "Active"
    },
    {
        "id": "STU2024047",
        "name": "Swathi Murthy",
        "email": "swathi.murthy@student.klmce.edu.in",
        "phone": "+91 92885 78386",
        "gender": "F",
        "dob": "2004-05-20",
        "region": "Kochi",
        "department": "Civil",
        "cgpa": 7.94,
        "year": 3,
        "attendance_pct": 85,
        "fee_status": "Paid",
        "status": "Active"
    },
    {
        "id": "STU2024048",
        "name": "Ananya Krishnan",
        "email": "ananya.krishnan@student.klmce.edu.in",
        "phone": "+91 97613 84691",
        "gender": "F",
        "dob": "2003-11-13",
        "region": "Bangalore",
        "department": "Computer Science",
        "cgpa": 8.13,
        "year": 3,
        "attendance_pct": 80,
        "fee_status": "Overdue",
        "status": "Active"
    },
    {
        "id": "STU2024049",
        "name": "Aishwarya Patel",
        "email": "aishwarya.patel@student.klmce.edu.in",
        "phone": "+91 94581 88139",
        "gender": "F",
        "dob": "2004-05-18",
        "region": "Chennai",
        "department": "Information Technology",
        "cgpa": 9.63,
        "year": 1,
        "attendance_pct": 82,
        "fee_status": "Overdue",
        "status": "Warning"
    },
    {
        "id": "STU2024050",
        "name": "Vishal Deshmukh",
        "email": "vishal.deshmukh@student.klmce.edu.in",
        "phone": "+91 97342 12260",
        "gender": "M",
        "dob": "1999-05-08",
        "region": "Hyderabad",
        "department": "Electronics",
        "cgpa": 7.3,
        "year": 3,
        "attendance_pct": 90,
        "fee_status": "Pending",
        "status": "Warning"
    }
];

export const FACULTY = [
    {
        "id": "FAC001",
        "name": "Prof. Nandini Gounder",
        "email": "nandini.gounder@klmce.edu.in",
        "phone": "+91 90047 42951",
        "department": "Mechanical",
        "designation": "Assistant Professor",
        "joining_date": "2021-04-01",
        "publications": 10,
        "courses_taught": 2
    },
    {
        "id": "FAC002",
        "name": "Prof. Sanjay Pillai",
        "email": "sanjay.pillai@klmce.edu.in",
        "phone": "+91 89060 87278",
        "department": "Information Technology",
        "designation": "HOD",
        "joining_date": "2011-04-01",
        "publications": 9,
        "courses_taught": 2
    },
    {
        "id": "FAC003",
        "name": "Dr. Anjali Singh",
        "email": "anjali.singh@klmce.edu.in",
        "phone": "+91 97502 26591",
        "department": "Electrical",
        "designation": "Assistant Professor",
        "joining_date": "2010-09-01",
        "publications": 9,
        "courses_taught": 4
    },
    {
        "id": "FAC004",
        "name": "Dr. Vishal Rao",
        "email": "vishal.rao@klmce.edu.in",
        "phone": "+91 98810 47268",
        "department": "Civil",
        "designation": "Professor",
        "joining_date": "2017-06-01",
        "publications": 5,
        "courses_taught": 2
    },
    {
        "id": "FAC005",
        "name": "Dr. Preeti Rao",
        "email": "preeti.rao@klmce.edu.in",
        "phone": "+91 93130 74454",
        "department": "Computer Science",
        "designation": "Assistant Professor",
        "joining_date": "2012-03-01",
        "publications": 9,
        "courses_taught": 2
    },
    {
        "id": "FAC006",
        "name": "Prof. Aditya Rao",
        "email": "aditya.rao@klmce.edu.in",
        "phone": "+91 99867 88135",
        "department": "Information Technology",
        "designation": "Associate Professor",
        "joining_date": "2022-09-01",
        "publications": 12,
        "courses_taught": 3
    },
    {
        "id": "FAC007",
        "name": "Prof. Meera Naidu",
        "email": "meera.naidu@klmce.edu.in",
        "phone": "+91 90006 84531",
        "department": "Information Technology",
        "designation": "Assistant Professor",
        "joining_date": "2019-12-01",
        "publications": 3,
        "courses_taught": 2
    },
    {
        "id": "FAC008",
        "name": "Dr. Vijay Nair",
        "email": "vijay.nair@klmce.edu.in",
        "phone": "+91 87859 32782",
        "department": "Information Technology",
        "designation": "Assistant Professor",
        "joining_date": "2012-01-01",
        "publications": 13,
        "courses_taught": 3
    },
    {
        "id": "FAC009",
        "name": "Dr. Meera Iyer",
        "email": "meera.iyer@klmce.edu.in",
        "phone": "+91 89440 47056",
        "department": "Electronics",
        "designation": "Professor",
        "joining_date": "2011-11-01",
        "publications": 7,
        "courses_taught": 3
    },
    {
        "id": "FAC010",
        "name": "Dr. Manoj Rao",
        "email": "manoj.rao@klmce.edu.in",
        "phone": "+91 84882 44816",
        "department": "Mechanical",
        "designation": "Assistant Professor",
        "joining_date": "2010-03-01",
        "publications": 9,
        "courses_taught": 4
    },
    {
        "id": "FAC011",
        "name": "Prof. Ananya Rao",
        "email": "ananya.rao@klmce.edu.in",
        "phone": "+91 89964 62757",
        "department": "Electrical",
        "designation": "Professor",
        "joining_date": "2017-02-01",
        "publications": 1,
        "courses_taught": 3
    },
    {
        "id": "FAC012",
        "name": "Dr. Aishwarya Kumar",
        "email": "aishwarya.kumar@klmce.edu.in",
        "phone": "+91 87501 98381",
        "department": "Information Technology",
        "designation": "Assistant Professor",
        "joining_date": "2022-11-01",
        "publications": 8,
        "courses_taught": 4
    },
    {
        "id": "FAC013",
        "name": "Prof. Siddharth Deshmukh",
        "email": "siddharth.deshmukh@klmce.edu.in",
        "phone": "+91 89114 33788",
        "department": "Information Technology",
        "designation": "Professor",
        "joining_date": "2020-08-01",
        "publications": 2,
        "courses_taught": 3
    },
    {
        "id": "FAC014",
        "name": "Prof. Lakshmi Patel",
        "email": "lakshmi.patel@klmce.edu.in",
        "phone": "+91 83427 31079",
        "department": "Electrical",
        "designation": "Professor",
        "joining_date": "2021-08-01",
        "publications": 9,
        "courses_taught": 4
    },
    {
        "id": "FAC015",
        "name": "Dr. Priya Gounder",
        "email": "priya.gounder@klmce.edu.in",
        "phone": "+91 90306 43082",
        "department": "Electrical",
        "designation": "Assistant Professor",
        "joining_date": "2022-07-01",
        "publications": 0,
        "courses_taught": 4
    },
    {
        "id": "FAC016",
        "name": "Dr. Lakshmi Iyer",
        "email": "lakshmi.iyer@klmce.edu.in",
        "phone": "+91 96988 57419",
        "department": "Information Technology",
        "designation": "Professor",
        "joining_date": "2020-08-01",
        "publications": 1,
        "courses_taught": 2
    },
    {
        "id": "FAC017",
        "name": "Prof. Swathi Singh",
        "email": "swathi.singh@klmce.edu.in",
        "phone": "+91 95883 25915",
        "department": "Computer Science",
        "designation": "Associate Professor",
        "joining_date": "2021-03-01",
        "publications": 9,
        "courses_taught": 4
    },
    {
        "id": "FAC018",
        "name": "Dr. Naveen Murthy",
        "email": "naveen.murthy@klmce.edu.in",
        "phone": "+91 87362 24871",
        "department": "Civil",
        "designation": "Assistant Professor",
        "joining_date": "2020-03-01",
        "publications": 15,
        "courses_taught": 4
    },
    {
        "id": "FAC019",
        "name": "Prof. Sruthi Sharma",
        "email": "sruthi.sharma@klmce.edu.in",
        "phone": "+91 95810 71894",
        "department": "Mechanical",
        "designation": "Professor",
        "joining_date": "2018-03-01",
        "publications": 12,
        "courses_taught": 2
    },
    {
        "id": "FAC020",
        "name": "Prof. Rahul Sharma",
        "email": "rahul.sharma@klmce.edu.in",
        "phone": "+91 91137 76550",
        "department": "Electrical",
        "designation": "Assistant Professor",
        "joining_date": "2014-12-01",
        "publications": 9,
        "courses_taught": 4
    }
];

export const ADMINS = [
    {
        "id": "ADM001",
        "name": "Swathi Gounder",
        "email": "swathi.gounder@klmce.edu.in",
        "phone": "+91 87648 73483",
        "role": "Registrar",
        "access_level": "Superuser",
        "office_location": "Admin Block - Room 101"
    },
    {
        "id": "ADM002",
        "name": "Deepa Rao",
        "email": "deepa.rao@klmce.edu.in",
        "phone": "+91 94997 81228",
        "role": "Admissions Officer",
        "access_level": "Editor",
        "office_location": "Admin Block - Room 102"
    },
    {
        "id": "ADM003",
        "name": "Ananya Patel",
        "email": "ananya.patel@klmce.edu.in",
        "phone": "+91 98495 34727",
        "role": "Finance Head",
        "access_level": "Editor",
        "office_location": "Admin Block - Room 103"
    },
    {
        "id": "ADM004",
        "name": "Prashant Rajan",
        "email": "prashant.rajan@klmce.edu.in",
        "phone": "+91 77653 63841",
        "role": "Dean",
        "access_level": "Editor",
        "office_location": "Admin Block - Room 104"
    },
    {
        "id": "ADM005",
        "name": "Hari Deshmukh",
        "email": "hari.deshmukh@klmce.edu.in",
        "phone": "+91 93108 59968",
        "role": "System Admin",
        "access_level": "Editor",
        "office_location": "Admin Block - Room 105"
    }
];
